typography_spectrum: 0.8666947849560529
color:
  brandStrength: 0.5333119686692953
  lightness: 0.8166028435807675
  saturation: 0.2527935500256717
  rhythmicContrast: 0.0708858270663768
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
layout_spectrum: 0.8051999898161739
name: Brigde ROI
navigation:
  - name: Holding Company
    url: rebuild.group
    type: external
  - name: Is Bridge ROI for you?
    id: fcf7a6e1-3e0d-4aaf-b372-6ad2f7862e30
    type: content
title: Bridge Your ROI
description: >-
  A simple, affordable solution to track the return on your marketing
  investment, while demystifying more complex customer relationship management
  tools.
